name: Index Content

on:
  push:
    branches:
      - '**'
    paths:
      - content/**

jobs:
  index-content:
    name: index-content
    runs-on: ubuntu-18.04

    steps:
      - name: checkout.
        uses: actions/checkout@v2

      - name: Build the index.
        run:  find ./content/ -type f | jq -R -s -c 'split("\n")|.[0:-1]' | tee index/main.json

      - name: Add any index files.
        run:  git add ./index/*

      - name: Commit & push any if changes are found
        run:  |
          test -n "$(git status -s)" \
            && git \
              -c "user.name=index-bot" \
              -c "user.email=index-bot@seanmorr.is" \
              commit -nam 'Indexing content.' \
            && git push \
            || true
